### PR TITLE
Use Gio for file listing, add global keybinding to show menu

### LINKED ISSUE #6: Allow for keyboard control
So you don't need to use the mouse at all

### PR DESCRIPTION
**Pull request by jplitza**
The Gio part should be pretty straight forward.

The other commit fixes #6, with lots of code taken from [shell-hide-legacy-tray](/jonnylamb/shell-hide-legacy-tray). The default of <Super>w is, of course, open to debate. I just had to pick something.

### CODE REVIEW

**Comment by mcat95** [comment]
This looks good to me. It also settles the base to create a configuration dialog, and that's perfect. 

The only question is how hard would it be to implement focusing the listing when the extension is opened, so you can move through the passwords with the keyboard (vi style keybindings would be awesome, but that's for another time), because at the moment I can open the extension but can't navigate my passwords.

**Comment by jplitza** [comment]
This was harder than I thought, but now the menu is focused after pressing the hotkey. There are still some keyboard-use-only problems, the same as in eonpatapon/gnome-shell-extension-caffeine#75 for example, but I think it is usable now.

Also, I fixed spaces in filenames for good now (using the shell with "user-defined" content, like filenames, is a bad idea!)

**Comment by mcat95** [comment]
I added the focus call when getting inside a directory, and it looks great! Merging now

**Comment by mcat95** [comment]
Merged.

**Comment by jplitza** [comment]
Well, I should have been more patient with pushing, because now we both implemented that bit. ;-)

My implementation differs a bit, because I introduced a helper method for changing directories and on the way discarded the dot that always prefixed the path (we prefix it with .password-store/ anyway, so no dot is needed). You have to decide which version you want to have.

**Comment by mcat95** [comment]
Woops, my bad, I was too quick, let me review your version and I will do the merge

**Comment by mcat95** [comment]
Well, it's merged now with your version because I find it more clear. Thanks! :100:

**Comment by jplitza** [comment]
*I* have to thank *you* for being so responsive! That's how contributing in FOSS is fun.

Just noted one thing I don't yet know how to fix: When navigating with the arrow keys, the scroll popup doesn't scroll. The focused item simply isn't visible if your menu is very long.

**Pull request closed without merging**
